### ISSUE TITLE
Empêcher d'avoir 2 fois la même couleur

### ISSUE THREAD

**Issue by cprodhomme** [Gaviil/Hexagame#31]

**Comment by Qboussard** [comment]
<img width="714" alt="capture d ecran 2017-09-15 a 17 17 14" src="https://user-images.githubusercontent.com/6230697/30490277-c811f050-9a39-11e7-92d1-e50bf5f2cf6a.png">

pour moi je n'ai pas de bug sur master

premiere couleur c'est le choix et la deuxième c'est le nouveaux rand qu'il prend (et boucle jusqu'a être ok)

**Comment by cprodhomme** [comment]
En attente d'informations.
