### ISSUE TITLE
Popup d'aide

### ISSUE THREAD

**Issue by cprodhomme** [Gaviil/Hexagame#9]
Ajouter un bouton qui redirige vers une page/popup qui contient un texte explicatif

**Texte pour le mode Easy :** 

> Trouvez la bonne couleur à partir de son nom HTML en haut de l'écran

**Texte pour le mode Normal :** 

> Trouvez la bonne couleur à partir de son nom HTML en haut de l'écran **en moins de 3 secondes !**

**Texte pour le mode Hard :** 

> Trouvez la bonne couleur à partir de son code Hexadécimal en haut de l'écran

**Comment by Qboussard** [comment]
Update a tester
